# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\GitHubStorage\Course_and_Learning_resource\software_learning\3_pyqt_esytry\ui\settingUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(400, 500)
        self.SwitchButton = SwitchButton(Frame)
        self.SwitchButton.setGeometry(QtCore.QRect(200, 130, 76, 22))
        self.SwitchButton.setObjectName("SwitchButton")
        self.CaptionLabel = CaptionLabel(Frame)
        self.CaptionLabel.setGeometry(QtCore.QRect(50, 40, 91, 41))
        self.CaptionLabel.setObjectName("CaptionLabel")
        self.SubtitleLabel = SubtitleLabel(Frame)
        self.SubtitleLabel.setGeometry(QtCore.QRect(50, 120, 120, 27))
        self.SubtitleLabel.setObjectName("SubtitleLabel")
        self.SubtitleLabel_2 = SubtitleLabel(Frame)
        self.SubtitleLabel_2.setGeometry(QtCore.QRect(50, 200, 120, 27))
        self.SubtitleLabel_2.setObjectName("SubtitleLabel_2")
        self.SubtitleLabel_3 = SubtitleLabel(Frame)
        self.SubtitleLabel_3.setGeometry(QtCore.QRect(50, 260, 120, 27))
        self.SubtitleLabel_3.setObjectName("SubtitleLabel_3")
        self.PasswordLineEdit = PasswordLineEdit(Frame)
        self.PasswordLineEdit.setGeometry(QtCore.QRect(180, 260, 158, 33))
        self.PasswordLineEdit.setObjectName("PasswordLineEdit")
        self.PasswordLineEdit_2 = PasswordLineEdit(Frame)
        self.PasswordLineEdit_2.setGeometry(QtCore.QRect(180, 200, 158, 33))
        self.PasswordLineEdit_2.setObjectName("PasswordLineEdit_2")

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.CaptionLabel.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:16pt;\">👀设置</span></p></body></html>"))
        self.SubtitleLabel.setText(_translate("Frame", "窗口锁定"))
        self.SubtitleLabel_2.setText(_translate("Frame", "API账户"))
        self.SubtitleLabel_3.setText(_translate("Frame", "API密钥"))
from qfluentwidgets import CaptionLabel, PasswordLineEdit, SubtitleLabel, SwitchButton
