# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\GitHubStorage\Course_and_Learning_resource\software_learning\3_pyqt_esytry\ui\translation2.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Translation2(object):
    def setupUi(self, Translation2):
        Translation2.setObjectName("Translation2")
        Translation2.resize(400, 500)
        Translation2.setStyleSheet("")
        self.DropDownPushButton = DropDownPushButton(Translation2)
        self.DropDownPushButton.setGeometry(QtCore.QRect(180, 270, 194, 32))
        self.DropDownPushButton.setObjectName("DropDownPushButton")
        self.CaptionLabel = CaptionLabel(Translation2)
        self.CaptionLabel.setGeometry(QtCore.QRect(50, 20, 101, 32))
        self.CaptionLabel.setStyleSheet("FluentLabelBase {\n"
"    font: 9pt \"华文中宋\";\n"
"    color: black;\n"
"}\n"
"\n"
"HyperlinkLabel {\n"
"    color: #009faa;\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    text-align: left;\n"
"    padding: 0;\n"
"    margin: 0;\n"
"}\n"
"\n"
"HyperlinkLabel[underline=true] {\n"
"    text-decoration: underline;\n"
"}\n"
"\n"
"HyperlinkLabel[underline=false] {\n"
"    text-decoration: none;\n"
"}\n"
"\n"
"HyperlinkLabel:hover {\n"
"    color: #007780;\n"
"}\n"
"\n"
"HyperlinkLabel:pressed {\n"
"    color: #00a7b3;\n"
"}\n"
"FluentLabelBase{color:#ff000000}")
        self.CaptionLabel.setObjectName("CaptionLabel")
        self.PlainTextEdit = PlainTextEdit(Translation2)
        self.PlainTextEdit.setGeometry(QtCore.QRect(40, 310, 341, 160))
        self.PlainTextEdit.setPlainText("")
        self.PlainTextEdit.setObjectName("PlainTextEdit")
        self.BodyLabel = BodyLabel(Translation2)
        self.BodyLabel.setGeometry(QtCore.QRect(40, 70, 91, 19))
        self.BodyLabel.setObjectName("BodyLabel")
        self.BodyLabel_2 = BodyLabel(Translation2)
        self.BodyLabel_2.setGeometry(QtCore.QRect(40, 280, 91, 19))
        self.BodyLabel_2.setObjectName("BodyLabel_2")
        self.DropDownPushButton_2 = DropDownPushButton(Translation2)
        self.DropDownPushButton_2.setGeometry(QtCore.QRect(180, 65, 201, 32))
        self.DropDownPushButton_2.setObjectName("DropDownPushButton_2")
        self.PlainTextEdit_2 = PlainTextEdit(Translation2)
        self.PlainTextEdit_2.setGeometry(QtCore.QRect(40, 100, 341, 160))
        self.PlainTextEdit_2.setPlainText("")
        self.PlainTextEdit_2.setObjectName("PlainTextEdit_2")

        self.retranslateUi(Translation2)
        QtCore.QMetaObject.connectSlotsByName(Translation2)

    def retranslateUi(self, Translation2):
        _translate = QtCore.QCoreApplication.translate
        Translation2.setWindowTitle(_translate("Translation2", "Frame"))
        Translation2.setWhatsThis(_translate("Translation2", "<html><head/><body><p>TranslateUI</p><p><br/></p></body></html>"))
        self.DropDownPushButton.setText(_translate("Translation2", "Drop down push button"))
        self.CaptionLabel.setText(_translate("Translation2", "<html><head/><body><p><span style=\" font-size:18pt;\">🔡翻译</span></p></body></html>"))
        self.BodyLabel.setText(_translate("Translation2", "▶待翻译内容"))
        self.BodyLabel_2.setText(_translate("Translation2", "▶翻译结果"))
        self.DropDownPushButton_2.setText(_translate("Translation2", "Drop down push button"))
from qfluentwidgets import BodyLabel, CaptionLabel, DropDownPushButton, PlainTextEdit
