# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\GitHubStorage\Course_and_Learning_resource\software_learning\4_qtdesigner\translationUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_translation(object):
    def setupUi(self, translation):
        translation.setObjectName("translation")
        translation.resize(400, 500)
        self.SearchLineEdit = SearchLineEdit(translation)
        self.SearchLineEdit.setGeometry(QtCore.QRect(60, 110, 301, 33))
        self.SearchLineEdit.setObjectName("SearchLineEdit")
        self.PlainTextEdit = PlainTextEdit(translation)
        self.PlainTextEdit.setGeometry(QtCore.QRect(60, 200, 301, 261))
        self.PlainTextEdit.setObjectName("PlainTextEdit")
        self.CaptionLabel = CaptionLabel(translation)
        self.CaptionLabel.setGeometry(QtCore.QRect(50, 30, 91, 41))
        self.CaptionLabel.setStyleSheet("FluentLabelBase {\n"
"    font: 7pt \"黑体\";\n"
"    color: black;\n"
"}\n"
"\n"
"HyperlinkLabel {\n"
"    color: #009faa;\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    text-align: left;\n"
"    padding: 0;\n"
"    margin: 0;\n"
"}\n"
"\n"
"HyperlinkLabel[underline=true] {\n"
"    text-decoration: underline;\n"
"}\n"
"\n"
"HyperlinkLabel[underline=false] {\n"
"    text-decoration: none;\n"
"}\n"
"\n"
"HyperlinkLabel:hover {\n"
"    color: #007780;\n"
"}\n"
"\n"
"HyperlinkLabel:pressed {\n"
"    color: #00a7b3;\n"
"}\n"
"FluentLabelBase{color:#ff000000}")
        self.CaptionLabel.setObjectName("CaptionLabel")
        self.SubtitleLabel = SubtitleLabel(translation)
        self.SubtitleLabel.setGeometry(QtCore.QRect(60, 80, 120, 27))
        self.SubtitleLabel.setStyleSheet("FluentLabelBase {\n"
"    font: 7pt \"黑体\";\n"
"    color: black;\n"
"}\n"
"\n"
"HyperlinkLabel {\n"
"    color: #009faa;\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    text-align: left;\n"
"    padding: 0;\n"
"    margin: 0;\n"
"}\n"
"\n"
"HyperlinkLabel[underline=true] {\n"
"    text-decoration: underline;\n"
"}\n"
"\n"
"HyperlinkLabel[underline=false] {\n"
"    text-decoration: none;\n"
"}\n"
"\n"
"HyperlinkLabel:hover {\n"
"    color: #007780;\n"
"}\n"
"\n"
"HyperlinkLabel:pressed {\n"
"    color: #00a7b3;\n"
"}\n"
"FluentLabelBase{color:#ff000000}")
        self.SubtitleLabel.setObjectName("SubtitleLabel")
        self.SubtitleLabel_2 = SubtitleLabel(translation)
        self.SubtitleLabel_2.setGeometry(QtCore.QRect(60, 170, 120, 27))
        self.SubtitleLabel_2.setStyleSheet("FluentLabelBase {\n"
"    font: 7pt \"黑体\";\n"
"    color: black;\n"
"}\n"
"\n"
"HyperlinkLabel {\n"
"    color: #009faa;\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    text-align: left;\n"
"    padding: 0;\n"
"    margin: 0;\n"
"}\n"
"\n"
"HyperlinkLabel[underline=true] {\n"
"    text-decoration: underline;\n"
"}\n"
"\n"
"HyperlinkLabel[underline=false] {\n"
"    text-decoration: none;\n"
"}\n"
"\n"
"HyperlinkLabel:hover {\n"
"    color: #007780;\n"
"}\n"
"\n"
"HyperlinkLabel:pressed {\n"
"    color: #00a7b3;\n"
"}\n"
"FluentLabelBase{color:#ff000000}")
        self.SubtitleLabel_2.setObjectName("SubtitleLabel_2")
        self.DropDownPushButton = DropDownPushButton(translation)
        self.DropDownPushButton.setGeometry(QtCore.QRect(230, 75, 131, 32))
        self.DropDownPushButton.setObjectName("DropDownPushButton")

        self.retranslateUi(translation)
        QtCore.QMetaObject.connectSlotsByName(translation)

    def retranslateUi(self, translation):
        _translate = QtCore.QCoreApplication.translate
        translation.setWindowTitle(_translate("translation", "Frame"))
        self.CaptionLabel.setText(_translate("translation", "<html><head/><body><p><span style=\" font-size:18pt;\">🔡翻译</span></p></body></html>"))
        self.SubtitleLabel.setText(_translate("translation", "<html><head/><body><p><span style=\" font-size:12pt;\">▶待翻译内容：</span></p></body></html>"))
        self.SubtitleLabel_2.setText(_translate("translation", "<html><head/><body><p><span style=\" font-size:12pt;\">▶翻译结果</span></p></body></html>"))
        self.DropDownPushButton.setText(_translate("translation", "语言选择"))
from qfluentwidgets import CaptionLabel, DropDownPushButton, PlainTextEdit, SearchLineEdit, SubtitleLabel
