name: Build Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # 选择运行的操作系统，因为打包 Windows 应用，所以选用 windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # 选择 Python 版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller  # 安装 PyInstaller
        cd ./Translation/5_restruct_translation
        pip install -r requirements.txt

    - name: Build with PyInstaller
      run: |
        cd ./Translation/5_restruct_translation
        pyinstaller -w --add-data "./resource/*;." -i "./resource/logo.ico" -n "Translate Helper" --onefile main.py

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: translate-helper
        path: dist/