# name: Build Application

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: macos-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v4

#     - name: Set up Python 3.10
#       uses: actions/setup-python@v5
#       with:
#         python-version: '3.1'  # 选择 Python 版本

#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install pyinstaller  # 安装 PyInstaller
#         cd ./Translation/5_restruct_translation
#         pip install requests
#         pip install pyqt5
#         pip install "PyQt-Fluent-Widgets[full]"
#         pip install PyDeepLX

#     - name: Build with PyInstaller
#       run: |
#         cd ./Translation/5_restruct_translation
#         pyinstaller -w --add-data "./resource/*:." -i "./resource/logo.icns" -n "Translate Helper" --onedir main.py

#     - name: Upload Artifacts
#       uses: actions/upload-artifact@v4
#       with:
#         name: Translate Helper.exe
#         path: ./Translation/5_restruct_translation/dist/
