name: Build Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # 选择运行的操作系统，因为打包 Windows 应用，所以选用 windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'  # 选择 Python 版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller  # 安装 PyInstaller
        pip install transformers -U
        pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121

    - name: Build with PyInstaller
      run: |
        cd ./LM_Qwen
        pyinstaller --onefile try.py

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Qwen.exe
        path: ./LM_Qwen/dist/
